var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { css } from "styled-components";
export var StyledAvatarSpan = styled.span(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: inline-block;\n  border-radius: 50%;\n  position: relative;\n  overflow: visible;\n\n  width: 40px;\n  height: 40px;\n"], ["\n  display: inline-block;\n  border-radius: 50%;\n  position: relative;\n  overflow: visible;\n\n  width: 40px;\n  height: 40px;\n"])));
export var StyledAvatarContentSpan = styled.span(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: block;\n  postition: absolute;\n  top: 0;\n  left: 0;\n\n  width: 100%;\n  height: 100%;\n\n  border-radius: 50%;\n  background: #efefef;\n  background-size: cover;\n  background-position: center center;\n  overflow: hidden;\n\n  svg {\n    display: block;\n    width: 100%;\n    height: 100%;\n  }\n"], ["\n  display: block;\n  postition: absolute;\n  top: 0;\n  left: 0;\n\n  width: 100%;\n  height: 100%;\n\n  border-radius: 50%;\n  background: #efefef;\n  background-size: cover;\n  background-position: center center;\n  overflow: hidden;\n\n  svg {\n    display: block;\n    width: 100%;\n    height: 100%;\n  }\n"])));
export var StyledActivitySpan = styled.span(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: block;\n  position: absolute;\n  right: 0;\n  bottom: 0;\n  z-index: 2;\n\n  width: 10px;\n  height: 10px;\n\n  background: gray;\n  border-radius: 50%;\n\n  ", "\n"], ["\n  display: block;\n  position: absolute;\n  right: 0;\n  bottom: 0;\n  z-index: 2;\n\n  width: 10px;\n  height: 10px;\n\n  background: gray;\n  border-radius: 50%;\n\n  ",
    "\n"])), function (props) { return props.isActive && css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    background: green;\n  "], ["\n    background: green;\n  "]))); });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styles.js.map