var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { css } from "styled-components";
export var StyledModalDiv = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: fixed;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  z-index: 9999;\n\n  background: rgba(0, 0, 0, .93);\n  transform: scale(0);\n  opacity: 0;\n  transition: opacity .3s ease, transform 1s ease;\n\n  ", "\n"], ["\n  position: fixed;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  z-index: 9999;\n\n  background: rgba(0, 0, 0, .93);\n  transform: scale(0);\n  opacity: 0;\n  transition: opacity .3s ease, transform 1s ease;\n\n  ",
    "\n"])), function (props) { return props.isOpen && css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    transition: transform .3s ease, opacity .5s ease;\n    transform: scale(1);\n    opacity: 1;\n  "], ["\n    transition: transform .3s ease, opacity .5s ease;\n    transform: scale(1);\n    opacity: 1;\n  "]))); });
export var StyledModalContentDiv = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: absolute;\n  top: 40%;\n  left: 50%;\n  transform: translateX(-50%) translateY(-50%);\n\n  max-width: 100%;\n\n  text-align: center;\n  text-transform: none;\n  letter-spacing: 0;\n"], ["\n  position: absolute;\n  top: 40%;\n  left: 50%;\n  transform: translateX(-50%) translateY(-50%);\n\n  max-width: 100%;\n\n  text-align: center;\n  text-transform: none;\n  letter-spacing: 0;\n"])));
export var StyledCloseButton = styled.button(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  padding: 1em 1.25em;\n  background: transparent;\n  border: 0;\n\n  display: block;\n  position: fixed;\n  top: 0;\n  right: 0;\n  z-index: 9999;\n\n  &:hover {\n    cursor: pointer;\n  }\n\n  svg {\n    display: block;\n    transition: all .3s ease;\n  }\n\n  &:hover svg {\n    transform: scale(1.25);\n  }\n"], ["\n  padding: 1em 1.25em;\n  background: transparent;\n  border: 0;\n\n  display: block;\n  position: fixed;\n  top: 0;\n  right: 0;\n  z-index: 9999;\n\n  &:hover {\n    cursor: pointer;\n  }\n\n  svg {\n    display: block;\n    transition: all .3s ease;\n  }\n\n  &:hover svg {\n    transform: scale(1.25);\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styles.js.map